--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN_USER" 
   (	"ADMIN_ID" VARCHAR2(50 BYTE), 
	"ADMIN_PWD" VARCHAR2(200 BYTE), 
	"ADMIN_NAME" VARCHAR2(50 BYTE), 
	"ADMIN_STATUS" VARCHAR2(20 BYTE) DEFAULT 'NORMAL', 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADMIN_USER
SET DEFINE OFF;
Insert into SYSTEM.ADMIN_USER (ADMIN_ID,ADMIN_PWD,ADMIN_NAME,ADMIN_STATUS,CDATETIME) values ('admin','1234','관리자','NORMAL',to_date('26/06/02','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008542
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008542" ON "SYSTEM"."ADMIN_USER" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN_USER" MODIFY ("ADMIN_PWD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMIN_USER" ADD PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
