--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ATTENDANCE" 
   (	"ATTEND_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"ATTEND_DATE" DATE DEFAULT SYSDATE, 
	"POINT" NUMBER DEFAULT 10, 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ATTENDANCE
SET DEFINE OFF;
Insert into SYSTEM.ATTENDANCE (ATTEND_ID,USER_ID,ATTEND_DATE,POINT,CDATETIME) values (1,'test1234567',to_date('26/06/04','RR/MM/DD'),10,to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.ATTENDANCE (ATTEND_ID,USER_ID,ATTEND_DATE,POINT,CDATETIME) values (2,'test1234567',to_date('26/06/08','RR/MM/DD'),10,to_date('26/06/08','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_ATTENDANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ATTENDANCE" ON "SYSTEM"."ATTENDANCE" ("ATTEND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_ATTENDANCE_USER_DAY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_ATTENDANCE_USER_DAY" ON "SYSTEM"."ATTENDANCE" ("USER_ID", TRUNC("ATTEND_DATE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ATTENDANCE" MODIFY ("ATTEND_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATTENDANCE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATTENDANCE" MODIFY ("ATTEND_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATTENDANCE" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATTENDANCE" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATTENDANCE" ADD CONSTRAINT "PK_ATTENDANCE" PRIMARY KEY ("ATTEND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ATTENDANCE" ADD CONSTRAINT "FK_ATTENDANCE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
