--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."NOTIFICATION" 
   (	"NOTI_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"NOTI_TYPE" VARCHAR2(20 BYTE), 
	"REF_ID" NUMBER, 
	"IS_READ" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.NOTIFICATION
SET DEFINE OFF;
Insert into SYSTEM.NOTIFICATION (NOTI_ID,USER_ID,NOTI_TYPE,REF_ID,IS_READ,CDATETIME) values (1,'test01','COMMENT',1,'N',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.NOTIFICATION (NOTI_ID,USER_ID,NOTI_TYPE,REF_ID,IS_READ,CDATETIME) values (2,'test1234567','LIKE',23,'Y',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.NOTIFICATION (NOTI_ID,USER_ID,NOTI_TYPE,REF_ID,IS_READ,CDATETIME) values (3,'test1234567','COMMENT',23,'Y',to_date('26/06/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_NOTIFICATION" ON "SYSTEM"."NOTIFICATION" ("NOTI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOTIFICATION" MODIFY ("NOTI_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOTIFICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOTIFICATION" MODIFY ("NOTI_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOTIFICATION" MODIFY ("IS_READ" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOTIFICATION" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NOTIFICATION" ADD CONSTRAINT "FK_NOTIFICATION_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
