--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST_LIKE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POST_LIKE" 
   (	"LIKE_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.POST_LIKE
SET DEFINE OFF;
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (12,9,'test12345',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (4,2,'test12345',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (11,6,'test123456',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (9,9,'test123456',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (10,5,'test123456',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (13,9,'test1234567',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (14,5,'test1234567',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (15,14,'test1234567',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_LIKE (LIKE_ID,POST_ID,USER_ID,CDATETIME) values (16,23,'test12345',to_date('26/06/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008510
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008510" ON "SYSTEM"."POST_LIKE" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_POST_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_POST_LIKE" ON "SYSTEM"."POST_LIKE" ("USER_ID", "POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POST_LIKE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_LIKE" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_LIKE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_LIKE" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_LIKE" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."POST_LIKE" ADD CONSTRAINT "UK_POST_LIKE" UNIQUE ("USER_ID", "POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."POST_LIKE" ADD CONSTRAINT "UQ_POST_LIKE" UNIQUE ("POST_ID", "USER_ID")
  USING INDEX (CREATE UNIQUE INDEX "SYSTEM"."UK_POST_LIKE" ON "SYSTEM"."POST_LIKE" ("USER_ID", "POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_LIKE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_LIKE" ADD CONSTRAINT "FK_POST_LIKE_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."POST" ("POST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."POST_LIKE" ADD CONSTRAINT "FK_POST_LIKE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
