--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST_IMAGE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POST_IMAGE" 
   (	"IMG_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"IMG_NAME" VARCHAR2(200 BYTE), 
	"IMG_PATH" VARCHAR2(300 BYTE), 
	"IS_MAIN" CHAR(1 BYTE) DEFAULT 'N', 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.POST_IMAGE
SET DEFINE OFF;
Insert into SYSTEM.POST_IMAGE (IMG_ID,POST_ID,IMG_NAME,IMG_PATH,IS_MAIN,CDATETIME) values (4,6,'1780294884881_740917.png','/uploads/1780294884881_740917.png','Y',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_IMAGE (IMG_ID,POST_ID,IMG_NAME,IMG_PATH,IS_MAIN,CDATETIME) values (5,10,'1780368094175_653280.PNG','/uploads/1780368094175_653280.PNG','Y',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_IMAGE (IMG_ID,POST_ID,IMG_NAME,IMG_PATH,IS_MAIN,CDATETIME) values (3,5,'1780294858929_27977.png','/uploads/1780294858929_27977.png','Y',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_IMAGE (IMG_ID,POST_ID,IMG_NAME,IMG_PATH,IS_MAIN,CDATETIME) values (6,12,'1780373943280_708817.PNG','/uploads/1780373943280_708817.PNG','Y',to_date('26/06/02','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008528
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008528" ON "SYSTEM"."POST_IMAGE" ("IMG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POST_IMAGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_IMAGE" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_IMAGE" MODIFY ("IMG_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_IMAGE" MODIFY ("IMG_PATH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_IMAGE" MODIFY ("IS_MAIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_IMAGE" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_IMAGE" ADD PRIMARY KEY ("IMG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_IMAGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_IMAGE" ADD CONSTRAINT "FK_POST_IMAGE_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."POST" ("POST_ID") ENABLE;
