--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POST" 
   (	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"POST_TYPE" VARCHAR2(20 BYTE) DEFAULT 'FREE', 
	"EMOTION" VARCHAR2(20 BYTE), 
	"VIEW_CNT" NUMBER DEFAULT 0, 
	"LIKE_CNT" NUMBER DEFAULT 0, 
	"POST_STATUS" VARCHAR2(10 BYTE) DEFAULT 'NORMAL', 
	"CDATETIME" DATE DEFAULT SYSDATE, 
	"TEAM_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.POST
SET DEFINE OFF;
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (1,'test12345','ㅎㅇ','FREE',null,19,0,'NORMAL',to_date('26/06/01','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (2,'test12345','아니 몇연패여','CHEER',null,18,1,'DEL',to_date('26/06/01','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (5,'test12345','망곰','FREE',null,12,2,'NORMAL',to_date('26/06/01','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (6,'test12345','짱구','FREE',null,27,1,'NORMAL',to_date('26/06/01','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (9,'test123456','ㅎㅇ','CHEER',null,63,3,'NORMAL',to_date('26/06/01','RR/MM/DD'),3);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (10,'test123456','ㅊㅍㅊㅍㅊ','FREE',null,5,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (11,'test1234567','ㅎㅇ','FREE',null,0,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (12,'test1234567','두산테스트글입니다','FREE',null,5,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (13,'test1234567','두산테스트','CHEER',null,9,0,'DEL',to_date('26/06/02','RR/MM/DD'),2);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (14,'test1234567','테스트입니다','CHEER',null,25,1,'DEL',to_date('26/06/02','RR/MM/DD'),2);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (15,'test1234567','테스트2','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),2);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (16,'test1234567','테스트3','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (17,'test1234567','테스트4','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (18,'test1234567','테스트5','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (19,'test1234567','테스트6','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (20,'test1234567','테스트7','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (21,'test1234567','테스트8','FREE',null,2,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (22,'test1234567','기아테스트입니다','FREE',null,1,0,'DEL',to_date('26/06/02','RR/MM/DD'),null);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (23,'test1234567','기아테스트입니다','FREE',null,24,1,'NORMAL',to_date('26/06/02','RR/MM/DD'),4);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (24,'test1234567','ㅎㅇ','FREE',null,1,0,'DEL',to_date('26/06/04','RR/MM/DD'),2);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (25,'test1234567','두산','FREE',null,8,0,'NORMAL',to_date('26/06/04','RR/MM/DD'),2);
Insert into SYSTEM.POST (POST_ID,USER_ID,TITLE,POST_TYPE,EMOTION,VIEW_CNT,LIKE_CNT,POST_STATUS,CDATETIME,TEAM_ID) values (26,'test123456','테스트','FREE',null,3,0,'NORMAL',to_date('26/06/08','RR/MM/DD'),null);
--------------------------------------------------------
--  DDL for Index SYS_C008505
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008505" ON "SYSTEM"."POST" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("POST_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("VIEW_CNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("LIKE_CNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("POST_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST" ADD CONSTRAINT "CK_POST_TYPE" CHECK (POST_TYPE IN ('FREE', 'CHEER', 'INFO', 'REVIEW')) ENABLE;
  ALTER TABLE "SYSTEM"."POST" ADD CONSTRAINT "CK_POST_STATUS" CHECK (POST_STATUS IN ('NORMAL', 'DEL', 'BLOCK')) ENABLE;
  ALTER TABLE "SYSTEM"."POST" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST" ADD CONSTRAINT "FK_POST_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
