--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST_COMMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POST_COMMENT" 
   (	"COMMENT_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"PARENT_ID" NUMBER, 
	"CONTENT" VARCHAR2(500 BYTE), 
	"COMMENT_STATUS" VARCHAR2(10 BYTE) DEFAULT 'NORMAL', 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.POST_COMMENT
SET DEFINE OFF;
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (1,1,'test12345',null,'좋은글입니다','DEL',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (2,2,'test12345',null,'해체해라!!!!!!!!!!','NORMAL',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (3,6,'test123456',null,'ㅎㅇ','DEL',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (7,6,'test123456',null,'짱구다','DEL',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (5,9,'test123456',null,'ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ','DEL',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (6,9,'test123456',null,'ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ','NORMAL',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (8,14,'test1234567',null,'테스트댓글입니다','NORMAL',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,PARENT_ID,CONTENT,COMMENT_STATUS,CDATETIME) values (9,23,'test12345',null,'테스트','NORMAL',to_date('26/06/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008519
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008519" ON "SYSTEM"."POST_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POST_COMMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_COMMENT" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_COMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_COMMENT" MODIFY ("COMMENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_COMMENT" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."POST_COMMENT" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_COMMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POST_COMMENT" ADD CONSTRAINT "FK_COMMENT_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."POST" ("POST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."POST_COMMENT" ADD CONSTRAINT "FK_COMMENT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."POST_COMMENT" ADD CONSTRAINT "FK_COMMENT_PARENT" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "SYSTEM"."POST_COMMENT" ("COMMENT_ID") ENABLE;
