--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REPORT" 
   (	"REPORT_ID" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"TARGET_TYPE" VARCHAR2(20 BYTE), 
	"TARGET_ID" NUMBER, 
	"REASON" VARCHAR2(100 BYTE), 
	"REPORT_STATUS" VARCHAR2(20 BYTE) DEFAULT 'WAIT', 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.REPORT
SET DEFINE OFF;
Insert into SYSTEM.REPORT (REPORT_ID,USER_ID,TARGET_TYPE,TARGET_ID,REASON,REPORT_STATUS,CDATETIME) values (1,'test1234567','POST',23,'욕설','DONE',to_date('26/06/02','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008539
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008539" ON "SYSTEM"."REPORT" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPORT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPORT" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPORT" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPORT" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REPORT" ADD PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPORT" ADD CONSTRAINT "FK_REPORT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
