--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TEAM" 
   (	"TEAM_ID" NUMBER, 
	"TEAM_NAME" VARCHAR2(30 BYTE), 
	"MASCOT_NAME" VARCHAR2(30 BYTE), 
	"TEAM_COLOR" VARCHAR2(20 BYTE), 
	"TEAM_IMG" VARCHAR2(200 BYTE), 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TEAM
SET DEFINE OFF;
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (1,'LG','쌍둥이','#C30452',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (2,'두산','철웅이','#131230',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (3,'SSG','랜디','#CE0E2D',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (4,'KIA','호걸이','#EA0029',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (5,'삼성','블레오','#074CA1',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (6,'롯데','윈지','#041E42',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (7,'한화','수리','#FF6600',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (8,'KT','빅또리','#000000',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (9,'NC','단디','#315288',null,to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.TEAM (TEAM_ID,TEAM_NAME,MASCOT_NAME,TEAM_COLOR,TEAM_IMG,CDATETIME) values (10,'키움','턱돌이','#570514',null,to_date('26/05/29','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008471
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008471" ON "SYSTEM"."TEAM" ("TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TEAM" MODIFY ("TEAM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEAM" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TEAM" ADD PRIMARY KEY ("TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
