--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_FOLLOW
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USER_FOLLOW" 
   (	"FOLLOW_ID" NUMBER, 
	"FOLLOWER_ID" VARCHAR2(30 BYTE), 
	"FOLLOWING_ID" VARCHAR2(30 BYTE), 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USER_FOLLOW
SET DEFINE OFF;
Insert into SYSTEM.USER_FOLLOW (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CDATETIME) values (2,'test123456','test1234567',to_date('26/06/08','RR/MM/DD'));
Insert into SYSTEM.USER_FOLLOW (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CDATETIME) values (3,'test1234567','test123456',to_date('26/06/08','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_USER_FOLLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_USER_FOLLOW" ON "SYSTEM"."USER_FOLLOW" ("FOLLOW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_USER_FOLLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_USER_FOLLOW" ON "SYSTEM"."USER_FOLLOW" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_FOLLOW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_FOLLOW" MODIFY ("FOLLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_FOLLOW" MODIFY ("FOLLOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_FOLLOW" MODIFY ("FOLLOWING_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_FOLLOW" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_FOLLOW" ADD CONSTRAINT "PK_USER_FOLLOW" PRIMARY KEY ("FOLLOW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."USER_FOLLOW" ADD CONSTRAINT "UK_USER_FOLLOW" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_FOLLOW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_FOLLOW" ADD CONSTRAINT "FK_FOLLOWER_USER" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."USER_FOLLOW" ADD CONSTRAINT "FK_FOLLOWING_USER" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
