--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_TEAM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USER_TEAM" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"TEAM_ID" NUMBER, 
	"CDATETIME" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USER_TEAM
SET DEFINE OFF;
Insert into SYSTEM.USER_TEAM (USER_ID,TEAM_ID,CDATETIME) values ('test1234567',2,to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.USER_TEAM (USER_ID,TEAM_ID,CDATETIME) values ('test123456',3,to_date('26/06/02','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_USER_TEAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_USER_TEAM" ON "SYSTEM"."USER_TEAM" ("USER_ID", "TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_TEAM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_TEAM" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TEAM" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TEAM" MODIFY ("CDATETIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TEAM" ADD CONSTRAINT "PK_USER_TEAM" PRIMARY KEY ("USER_ID", "TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_TEAM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_TEAM" ADD CONSTRAINT "FK_USER_TEAM_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."USER_TEAM" ADD CONSTRAINT "FK_USER_TEAM_TEAM" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "SYSTEM"."TEAM" ("TEAM_ID") ENABLE;
