--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PWD" VARCHAR2(100 BYTE), 
	"NICKNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"PROFILE_IMG" VARCHAR2(500 BYTE), 
	"USER_STATUS" VARCHAR2(20 BYTE) DEFAULT 'NORMAL', 
	"CDATE" DATE DEFAULT SYSDATE, 
	"FAVORITE_TEAM" NUMBER, 
	"SOCIAL_TYPE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USERS
SET DEFINE OFF;
Insert into SYSTEM.USERS (USER_ID,USER_PWD,NICKNAME,EMAIL,PROFILE_IMG,USER_STATUS,CDATE,FAVORITE_TEAM,SOCIAL_TYPE) values ('test01','$2b$10$kycjtG9OpOpzEARa3xMH6uDg5UglX0d/C7MfrtQyyzmJLg5ERBcNK','홍길동','test@test.com',null,'NORMAL',to_date('26/05/29','RR/MM/DD'),null,null);
Insert into SYSTEM.USERS (USER_ID,USER_PWD,NICKNAME,EMAIL,PROFILE_IMG,USER_STATUS,CDATE,FAVORITE_TEAM,SOCIAL_TYPE) values ('test1234','test1234','김철수','test@naver.com',null,'NORMAL',to_date('26/05/29','RR/MM/DD'),null,null);
Insert into SYSTEM.USERS (USER_ID,USER_PWD,NICKNAME,EMAIL,PROFILE_IMG,USER_STATUS,CDATE,FAVORITE_TEAM,SOCIAL_TYPE) values ('test12345','$2b$10$J5Fz.ixYXsOfls8a7.PsyuBnv9JP8/9R1L1Zzu40b3eJMCMlvR2ui','망곰','test@naver.com','/uploads/profile/1780297073536_992139.png','NORMAL',to_date('26/05/29','RR/MM/DD'),null,null);
Insert into SYSTEM.USERS (USER_ID,USER_PWD,NICKNAME,EMAIL,PROFILE_IMG,USER_STATUS,CDATE,FAVORITE_TEAM,SOCIAL_TYPE) values ('test123456','$2b$10$kzvL//WU9dKNCn9Z/YRPtunxvf8KF0t7LufpWPKINPXKlEq.OP/0m','흰둥이','test1234@naver.com','/uploads/profile/1780302668639_230676.png','NORMAL',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.USERS (USER_ID,USER_PWD,NICKNAME,EMAIL,PROFILE_IMG,USER_STATUS,CDATE,FAVORITE_TEAM,SOCIAL_TYPE) values ('test1234567','$2b$10$yvX.0iFSRO2QEsUuU3rQ5e4ZtVafrcIPzKigRT0MDr6HyDbwh9O.i','기영','test@gmail.com',null,'NORMAL',to_date('26/06/02','RR/MM/DD'),null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008467
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008467" ON "SYSTEM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
